### PR TITLE
adding test file

### PR DESCRIPTION
**Pull request by akshattripathi**

### CODE REVIEW

**Review by gnarayan — CHANGES_REQUESTED** [review]
AHA - so this is why we do PRs. This file is in the root directory of the repo. Not your own directory. Please fix - you can `git mv` the file and then push again and it should update your pull request

**Comment by akshattripathi** [comment]
> AHA - so this is why we do PRs. This file is in the root directory of the repo. Not your own directory. Please fix - you can `git mv` the file and then push again and it should update your pull request

All right, I just made a new pull request

**Comment by akshattripathi** [comment]
I realize that I should've done 'git mv' as you suggested, instead of creating a new request...will keep this mind next time :)

**Comment by gnarayan** [comment]
@akshattripathi  opened a separate PR #17 so this is now redundant.

**Pull request closed without merging**
